# Generated by Django 4.1.5 on 2023-10-02 16:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("year", models.PositiveIntegerField()),
                ("origin", models.CharField(default="France", max_length=100)),
                ("registration_date", models.DateField()),
                ("technical_inspection", models.BooleanField(default=False)),
                ("first_hand", models.BooleanField()),
                ("mileage", models.FloatField()),
                ("fuel_type", models.CharField(max_length=100)),
                ("transmission", models.CharField(max_length=100)),
                ("num_doors", models.PositiveIntegerField()),
                ("num_seats", models.PositiveIntegerField()),
                ("power", models.CharField(max_length=100)),
                ("co2_emission", models.FloatField()),
                ("length", models.FloatField()),
                ("trunk_volume", models.FloatField()),
                ("critair_rating", models.IntegerField()),
                ("combined_consumption", models.CharField(max_length=100)),
            ],
        ),
    ]
